package com.erpapproid.core.common.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {

    INVALID_INPUT(HttpStatus.BAD_REQUEST, "INVALID_INPUT"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
    NOT_FOUND(HttpStatus.NOT_FOUND, "NOT_FOUND"),
    INVALID_STATE_TRANSITION(HttpStatus.CONFLICT, "INVALID_STATE_TRANSITION"),
    DUPLICATE(HttpStatus.CONFLICT, "DUPLICATE"),
    IN_USE(HttpStatus.CONFLICT, "IN_USE"),
    BUSINESS_RULE_VIOLATION(HttpStatus.UNPROCESSABLE_ENTITY, "BUSINESS_RULE_VIOLATION"),
    UPSTREAM_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "UPSTREAM_UNAVAILABLE"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR"),

    ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "ITEM_NOT_FOUND"),
    ITEM_NO_DUPLICATE(HttpStatus.CONFLICT, "ITEM_NO_DUPLICATE"),
    ITEM_IN_USE(HttpStatus.CONFLICT, "ITEM_IN_USE"),
    PARTNER_NOT_FOUND(HttpStatus.NOT_FOUND, "PARTNER_NOT_FOUND"),
    PARTNER_IN_USE(HttpStatus.CONFLICT, "PARTNER_IN_USE"),
    BOM_DUPLICATE(HttpStatus.CONFLICT, "BOM_DUPLICATE"),
    BOM_IN_USE(HttpStatus.CONFLICT, "BOM_IN_USE"),
    ROUTING_NOT_FOUND(HttpStatus.NOT_FOUND, "ROUTING_NOT_FOUND"),
    ROUTING_SEQ_DUPLICATE(HttpStatus.CONFLICT, "ROUTING_SEQ_DUPLICATE"),
    ROUTING_IN_USE(HttpStatus.CONFLICT, "ROUTING_IN_USE"),
    QUOTATION_NOT_FOUND(HttpStatus.NOT_FOUND, "QUOTATION_NOT_FOUND"),
    SALES_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "SALES_ORDER_NOT_FOUND"),
    SHIPMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "SHIPMENT_NOT_FOUND"),
    WORK_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "WORK_ORDER_NOT_FOUND"),
    PURCHASE_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "PURCHASE_ORDER_NOT_FOUND"),
    PURCHASE_ORDER_CLOSED(HttpStatus.CONFLICT, "PURCHASE_ORDER_CLOSED"),
    RECEIVED_QTY_EXCEEDS_ORDER(HttpStatus.UNPROCESSABLE_ENTITY, "RECEIVED_QTY_EXCEEDS_ORDER"),
    GOOD_QTY_ZERO(HttpStatus.UNPROCESSABLE_ENTITY, "GOOD_QTY_ZERO"),
    INSUFFICIENT_STOCK(HttpStatus.UNPROCESSABLE_ENTITY, "INSUFFICIENT_STOCK"),
    ITEM_NOT_PRODUCIBLE(HttpStatus.UNPROCESSABLE_ENTITY, "ITEM_NOT_PRODUCIBLE"),
    PLAN_DUPLICATE(HttpStatus.CONFLICT, "PLAN_DUPLICATE"),
    LOT_NOT_FOUND(HttpStatus.NOT_FOUND, "LOT_NOT_FOUND");

    private final HttpStatus status;
    private final String code;

    ErrorCode(HttpStatus status, String code) {
        this.status = status;
        this.code = code;
    }

    public HttpStatus getStatus() {
        return status;
    }

    public String getCode() {
        return code;
    }
}
