import { test, expect } from '@playwright/test'
import { api, authenticated, futureDate, login, mutation, newItem, read, search, transition } from './helpers'
import type { components } from '../src/api/generated/core'

test('quotation → sales confirmation → production → shipment persists stock and revenue once', async ({ page, request }, info) => {
    const headers = await authenticated(request)
    const item = await newItem(request, headers)
    const partners: Required<components['schemas']['PartnerResponse']>[] = await read(request, 'partners?size=100', headers).then(r => r.content)
    const customer = partners.find(p => p.partnerType === '고객사')!
    expect(customer).toBeDefined()
    await login(page)
    await page.goto('/sales/quotations')
    await page.getByRole('button', { name: '견적 등록', exact: true }).click()
    const quotationNo = `QT-E2E-${Date.now()}`
    await page.getByLabel('견적번호 *', { exact: true }).fill(quotationNo)
    await page.getByLabel('고객사 *', { exact: true }).selectOption(String(customer.id))
    await page.getByLabel('품목 *', { exact: true }).selectOption(String(item.id))
    await page.getByLabel('수량 *', { exact: true }).fill('10')
    await page.getByLabel('단가(원) *', { exact: true }).fill('100')
    await expect(page.getByRole('button', { name: '납기 달력 열기' })).toBeVisible()
    await page.getByLabel('납기 *', { exact: true }).fill(futureDate())
    await page.getByLabel('유효기간 *', { exact: true }).fill(futureDate())
    const quotationResponse = mutation(page, 'quotations', 201)
    await page.getByRole('button', { name: '등록', exact: true }).click()
    const quotation = await quotationResponse
    const quoteRow = await search(page, '견적번호, 고객사, 품번 검색...', quotationNo)
    await transition(page, quoteRow, '발송')
    await expect(quoteRow).toContainText('발송완료')
    const orderResponse = mutation(page, `sales-orders/from-quotation/${quotation.id}`, 201)
    await transition(page, quoteRow, '수주 전환')
    const order = await orderResponse
    await page.getByRole('link', { name: '수주 보기', exact: true }).click()
    const orderRow = await search(page, '수주번호, 고객사, 품번 검색...', order.salesOrderNo)
    const confirmationResponse = mutation(page, `sales-orders/${order.id}/confirm`)
    await transition(page, orderRow, '수주 확정')
    const confirmation = await confirmationResponse
    await page.getByRole('link', { name: '작업오더 보기', exact: true }).click()
    const workRow = await search(page, '작업오더, 수주, 품번, 담당자 검색...', confirmation.workOrderNo)
    await workRow.getByRole('button', { name: '실적 입력', exact: true }).click()
    await page.getByLabel('누적 양품 *', { exact: true }).fill('4')
    await page.getByLabel('누적 불량 *', { exact: true }).fill('0')
    await page.getByRole('button', { name: '실적 입력 확인', exact: true }).click()
    await expect(workRow).toContainText('진행중')
    await workRow.getByRole('button', { name: '생산완료', exact: true }).click()
    await page.getByLabel('누적 양품 *', { exact: true }).fill('10')
    const completedResponse = mutation(page, `work-orders/${confirmation.workOrderId}/complete`)
    await page.getByRole('button', { name: '생산완료 확인', exact: true }).click()
    const completed = await completedResponse
    await expect(workRow).toContainText('완료')
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(10)
    const lots: Required<components['schemas']['LotResponse']>[] = await read(request, `lots?itemId=${item.id}`, headers)
    const lot = lots.find(l => l.lotNo === completed.lotNo)!
    expect(lot.qty).toBe(10)
    await page.goto('/sales/shipments')
    await page.getByRole('button', { name: '출하 지시', exact: true }).click()
    await page.getByLabel('수주번호 *', { exact: true }).selectOption(String(order.id))
    await page.getByLabel('출하 Lot *', { exact: true }).selectOption(String(lot.id))
    await page.getByLabel('출하 수량 *', { exact: true }).fill('10')
    await page.getByLabel('배송 예정일 *', { exact: true }).fill(futureDate())
    await page.getByLabel('차량', { exact: true }).fill('E2E truck')
    const shipmentResponse = mutation(page, 'shipments', 201)
    await page.getByRole('button', { name: '저장', exact: true }).click()
    const shipment = await shipmentResponse
    const shipmentRow = await search(page, '출하번호, 고객사, 품번 검색...', shipment.shipmentNo)
    await transition(page, shipmentRow, '배차')
    await expect(shipmentRow).toContainText('배차')
    await transition(page, shipmentRow, '출발')
    await expect(shipmentRow).toContainText('출발')
    const shippedResponse = mutation(page, `shipments/${shipment.id}/confirm`)
    await transition(page, shipmentRow, '출하 확정')
    const shipped = await shippedResponse
    expect(shipped.shipment.amount).toBe(1000)
    expect(shipped.receivableNo).toBeTruthy()
    expect(shipped.inventoryTxnNo).toBeTruthy()
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    expect((await read(request, `lots?itemId=${item.id}`, headers))[0].qty).toBe(0)
    expect((await read(request, `sales-orders/${order.id}`, headers)).status).toBe('출하완료')
    const duplicate = await request.post(`${api}/shipments/${shipment.id}/confirm`, { headers, data: {} })
    expect(duplicate.status()).toBe(409)
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    expect((await read(request, `shipments/${shipment.id}`, headers)).receivableNo).toBe(shipped.receivableNo)
    await page.reload()
    const persisted = await search(page, '출하번호, 고객사, 품번 검색...', shipment.shipmentNo)
    await persisted.getByRole('button', { name: '상세', exact: true }).click()
    const detail = page.getByRole('dialog')
    await expect(detail).toContainText(shipped.receivableNo)
    await expect(detail).toContainText(shipped.inventoryTxnNo)
    await expect(detail).toContainText(completed.lotNo)
    await page.screenshot({ path: info.outputPath('shipment-persisted.png'), fullPage: true })
})

test('material browser partial receiving and cancellation reverse only good stock', async ({ page, request }, info) => {
    const headers = await authenticated(request)
    const item = await newItem(request, headers, '자재')
    const partners: Required<components['schemas']['PartnerResponse']>[] = await read(request, 'partners?size=100', headers).then(r => r.content)
    const vendor = partners.find(p => p.partnerType === '발주처')!
    expect(vendor).toBeDefined()
    const created = await request.post(`${api}/purchase-orders`, { headers, data: {
        purchaseOrderNo: `PO-E2E-${Date.now()}`, vendorId: vendor.id, itemId: item.id, qty: 10, unitPrice: 100, dueDate: futureDate(),
    } })
    expect(created.status()).toBe(201)
    const order = await created.json()
    await login(page, 'e2e-material')
    await page.goto('/purchase/receiving')
    await page.getByRole('button', { name: '입고 등록', exact: true }).click()
    await page.getByLabel('발주번호 *', { exact: true }).selectOption(String(order.id))
    await page.getByLabel('총 입고수량 *', { exact: true }).fill('6')
    await page.getByLabel('불량수량 *', { exact: true }).fill('1')
    const receivedResponse = mutation(page, 'receivings', 201)
    await page.getByRole('button', { name: '등록', exact: true }).click()
    const received = await receivedResponse
    const row = await search(page, '입고번호, 발주번호, 발주처, 품번 검색...', received.receiving.receivingNo)
    await expect(row).toContainText('부분합격')
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(5)
    expect((await read(request, `purchase-orders/${order.id}`, headers)).receivedQty).toBe(6)
    await transition(page, row, '입고 취소')
    await expect(row).toContainText('취소')
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    const cancelled = await read(request, `receivings/${received.receiving.id}`, headers)
    expect(cancelled.reversalTxnNo).toBeTruthy()
    expect((await read(request, `purchase-orders/${order.id}`, headers)).receivedQty).toBe(0)
    await page.reload()
    const persisted = await search(page, '입고번호, 발주번호, 발주처, 품번 검색...', received.receiving.receivingNo)
    await persisted.getByRole('button', { name: '상세', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText(cancelled.reversalTxnNo)
    await page.screenshot({ path: info.outputPath('receiving-reversed.png'), fullPage: true })
})

test('protected return URL, rejected login, session restoration and logout', async ({ page, request }) => {
    expect((await request.get(`${api}/items`)).status()).toBe(401)
    await page.goto('/sales/quotations')
    await expect(page).toHaveURL(/\/login/)
    await page.getByLabel('사용자명').fill('admin')
    await page.getByLabel('비밀번호', { exact: true }).fill('incorrect')
    await page.getByRole('button', { name: '로그인', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('추적 ID:')
    await page.getByLabel('비밀번호', { exact: true }).fill('admin123')
    await page.getByRole('button', { name: '로그인', exact: true }).click()
    await expect(page).toHaveURL(/\/sales\/quotations$/)
    await page.reload()
    await expect(page.getByRole('button', { name: '견적 등록', exact: true })).toBeVisible()
    const user = await read(request, 'auth/me', await authenticated(request))
    await page.getByRole('button', { name: user.name, exact: true }).click()
    await page.getByRole('button', { name: '로그아웃', exact: true }).click()
    await expect(page).toHaveURL(/\/login/)
    await page.goto('/sales/quotations')
    await expect(page).toHaveURL(/\/login/)
})

test('material cannot write sales/production; sales cannot write receiving', async ({ page, request }) => {
    const material = await authenticated(request, 'e2e-material')
    const denied = await request.post(`${api}/shipments`, { headers: material, data: { salesOrderId: 1, lotId: 1, qty: 1, deliveryDate: futureDate() } })
    expect(denied.status()).toBe(403)
    await login(page, 'e2e-material')
    for (const [path, button] of [['/sales/quotations', '견적 등록'], ['/sales/orders', '수주 등록'],
        ['/production/orders', '오더 등록'], ['/sales/shipments', '출하 지시']]) {
        await page.goto(path)
        await expect(page.getByRole('table')).toBeVisible()
        await expect(page.getByRole('button', { name: button, exact: true })).toHaveCount(0)
    }
    const sales = await authenticated(request, 'e2e-sales')
    expect((await request.post(`${api}/receivings`, { headers: sales, data: { purchaseOrderId: 1, receivedQty: 1, defectQty: 0 } })).status()).toBe(403)
    // Remove the prior browser token through the real logout UI.
    await page.getByRole('button', { name: 'e2e-material', exact: true }).click()
    await page.getByRole('button', { name: '로그아웃', exact: true }).click()
    await login(page, 'e2e-sales')
    await page.goto('/purchase/receiving')
    await expect(page.getByRole('table')).toBeVisible()
    await expect(page.getByRole('button', { name: '입고 등록', exact: true })).toHaveCount(0)
})
