import { test, expect } from '@playwright/test'
import { api, authenticated, futureDate, login, mutation, newItem, read, search, transition } from './helpers'
import type { components } from '../src/api/generated/core'
import { seoulToday } from '../src/api/dashboard'
import { addDateDays } from '../src/api/mrp'

test('quotation → sales confirmation → production → shipment persists stock and revenue once', async ({ page, request }, info) => {
    const headers = await authenticated(request)
    const item = await newItem(request, headers)
    const partners: Required<components['schemas']['PartnerResponse']>[] = await read(request, 'partners?size=100', headers).then(r => r.content)
    const customer = partners.find(p => p.partnerType === '고객사')!
    expect(customer).toBeDefined()
    await login(page)
    await page.goto('/sales/quotations')
    await page.getByRole('button', { name: '견적 등록', exact: true }).click()
    const quotationNo = `QT-E2E-${Date.now()}`
    await page.getByLabel('견적번호 *', { exact: true }).fill(quotationNo)
    await page.getByLabel('고객사 *', { exact: true }).selectOption(String(customer.id))
    await page.getByLabel('품목 *', { exact: true }).selectOption(String(item.id))
    await page.getByLabel('수량 *', { exact: true }).fill('10')
    await page.getByLabel('단가(원) *', { exact: true }).fill('100')
    await expect(page.getByRole('button', { name: '납기 달력 열기' })).toBeVisible()
    await page.getByLabel('납기 *', { exact: true }).fill(futureDate())
    await page.getByLabel('유효기간 *', { exact: true }).fill(futureDate())
    const quotationResponse = mutation(page, 'quotations', 201)
    await page.getByRole('button', { name: '등록', exact: true }).click()
    const quotation = await quotationResponse
    const quoteRow = await search(page, '견적번호, 고객사, 품번 검색...', quotationNo)
    await transition(page, quoteRow, '발송')
    await expect(quoteRow).toContainText('발송완료')
    const orderResponse = mutation(page, `sales-orders/from-quotation/${quotation.id}`, 201)
    await transition(page, quoteRow, '수주 전환')
    const order = await orderResponse
    await page.getByRole('link', { name: '수주 보기', exact: true }).click()
    const orderRow = await search(page, '수주번호, 고객사, 품번 검색...', order.salesOrderNo)
    const confirmationResponse = mutation(page, `sales-orders/${order.id}/confirm`)
    await transition(page, orderRow, '수주 확정')
    const confirmation = await confirmationResponse
    await page.getByRole('link', { name: '작업오더 보기', exact: true }).click()
    const workRow = await search(page, '작업오더, 수주, 품번, 담당자 검색...', confirmation.workOrderNo)
    await workRow.getByRole('button', { name: '실적 입력', exact: true }).click()
    await page.getByLabel('누적 양품 *', { exact: true }).fill('4')
    await page.getByLabel('누적 불량 *', { exact: true }).fill('0')
    await page.getByRole('button', { name: '실적 입력 확인', exact: true }).click()
    await expect(workRow).toContainText('진행중')
    await workRow.getByRole('button', { name: '생산완료', exact: true }).click()
    await page.getByLabel('누적 양품 *', { exact: true }).fill('10')
    const completedResponse = mutation(page, `work-orders/${confirmation.workOrderId}/complete`)
    await page.getByRole('button', { name: '생산완료 확인', exact: true }).click()
    const completed = await completedResponse
    await expect(workRow).toContainText('완료')
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(10)
    const lots: Required<components['schemas']['LotResponse']>[] = await read(request, `lots?itemId=${item.id}`, headers)
    const lot = lots.find(l => l.lotNo === completed.lotNo)!
    expect(lot.qty).toBe(10)
    await page.goto('/sales/shipments')
    await page.getByRole('button', { name: '출하 지시', exact: true }).click()
    await page.getByLabel('수주번호 *', { exact: true }).selectOption(String(order.id))
    await page.getByLabel('출하 Lot *', { exact: true }).selectOption(String(lot.id))
    await page.getByLabel('출하 수량 *', { exact: true }).fill('10')
    await page.getByLabel('배송 예정일 *', { exact: true }).fill(futureDate())
    await page.getByLabel('차량', { exact: true }).fill('E2E truck')
    const shipmentResponse = mutation(page, 'shipments', 201)
    await page.getByRole('button', { name: '저장', exact: true }).click()
    const shipment = await shipmentResponse
    const shipmentRow = await search(page, '출하번호, 고객사, 품번 검색...', shipment.shipmentNo)
    await transition(page, shipmentRow, '배차')
    await expect(shipmentRow).toContainText('배차')
    await transition(page, shipmentRow, '출발')
    await expect(shipmentRow).toContainText('출발')
    const shippedResponse = mutation(page, `shipments/${shipment.id}/confirm`)
    await transition(page, shipmentRow, '출하 확정')
    const shipped = await shippedResponse
    expect(shipped.shipment.amount).toBe(1000)
    expect(shipped.receivableNo).toBeTruthy()
    expect(shipped.inventoryTxnNo).toBeTruthy()
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    expect((await read(request, `lots?itemId=${item.id}`, headers))[0].qty).toBe(0)
    expect((await read(request, `sales-orders/${order.id}`, headers)).status).toBe('출하완료')
    const duplicate = await request.post(`${api}/shipments/${shipment.id}/confirm`, { headers, data: {} })
    expect(duplicate.status()).toBe(409)
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    expect((await read(request, `shipments/${shipment.id}`, headers)).receivableNo).toBe(shipped.receivableNo)
    await page.reload()
    const persisted = await search(page, '출하번호, 고객사, 품번 검색...', shipment.shipmentNo)
    await persisted.getByRole('button', { name: '상세', exact: true }).click()
    const detail = page.getByRole('dialog')
    await expect(detail).toContainText(shipped.receivableNo)
    await expect(detail).toContainText(shipped.inventoryTxnNo)
    await expect(detail).toContainText(completed.lotNo)
    await page.screenshot({ path: info.outputPath('shipment-persisted.png'), fullPage: true })
    await page.goto(`/inventory/lots?itemId=${item.id}`)
    await page.getByRole('button', { name: completed.lotNo, exact: true }).click()
    const lotDialog = page.getByRole('dialog')
    const trace = await read(request, `lot-traces/${lot.id}`, headers)
    expect(trace.movements.content).toHaveLength(2)
    expect(trace.movements.content.map((m: { sourceType: string }) => m.sourceType).sort()).toEqual(['SHIPMENT', 'WORK_ORDER'])
    await expect(lotDialog.getByRole('link', { name: `WORK_ORDER · ${confirmation.workOrderNo}`, exact: true })).toBeVisible()
    await expect(lotDialog.getByRole('link', { name: `SHIPMENT · ${shipment.shipmentNo}`, exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath('lot-production-shipment.png'), fullPage: true })
    await lotDialog.getByRole('link', { name: `SHIPMENT · ${shipment.shipmentNo}`, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/sales/shipments\\?keyword=${shipment.shipmentNo}$`))
    await expect(page.getByRole('row').filter({ has: page.getByText(shipment.shipmentNo, { exact: true }) })).toContainText('출하완료')
    // Read the same persisted documents through Spring analytics (no network mocks).
    await page.goto('/')
    await expect(page.getByLabel('조회 시작일', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    await expect(page.getByLabel('조회 품목', { exact: true })).toHaveCSS('color', 'rgb(255, 255, 255)')
    await page.getByLabel('조회 품목', { exact: true }).selectOption(String(item.id))
    await page.getByRole('button', { name: '조회 적용', exact: true }).click()
    const kpis = page.getByRole('region', { name: '운영 KPI' })
    await expect(kpis.getByText('₩1,000', { exact: true })).toHaveCount(2)
    await expect(kpis.getByText('₩0', { exact: true })).toHaveCount(1)
    await expect(page.getByText('잔고 0건 · 납기준수 0/0건 · 기간 내 생산완료 1건', { exact: true })).toBeVisible()
    await expect(page.getByText('현재 위험 알림이 없습니다.', { exact: true })).toBeVisible()
    const dashboard = await read(request, `analytics/dashboard?itemId=${item.id}`, headers)
    expect(dashboard.kpis).toMatchObject({ revenueKrw: 1000, productionValueKrw: 1000, backlogKrw: 0,
        completedWorkOrders: 1, meanOrderDefectPercent: 0, inventoryTurnover: null })
    await page.reload()
    await page.getByLabel('조회 품목', { exact: true }).selectOption(String(item.id))
    await page.getByRole('button', { name: '조회 적용', exact: true }).click()
    await expect(kpis.getByText('₩1,000', { exact: true })).toHaveCount(2)
    await page.screenshot({ path: info.outputPath('dashboard-persisted.png'), fullPage: true })
    const salesLink = page.getByRole('link', { name: '실제 영업·미수 요약', exact: true })
    await expect(salesLink).toHaveAttribute('href', `/analytics/sales?itemId=${item.id}`)
    await salesLink.click()
    await expect(page.getByLabel('영업 품목', { exact: true })).toHaveValue(String(item.id))
    await expect(page.getByLabel('실적 시작일', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    const analysis = await read(request, `analytics/sales/summary?itemId=${item.id}`, headers)
    expect(analysis.summary).toMatchObject({ periodOrderKrw: 1000, periodRevenueKrw: 1000, knownCurrentBacklogKrw: 0,
        currentOpenReceivableKrw: 1000, currentOverdueReceivableKrw: 0, unknownBacklogOrders: 0 })
    const analysisRow = page.getByRole('row').filter({ has: page.getByRole('link', { name: order.salesOrderNo, exact: true }) })
    await expect(analysisRow).toContainText('출하완료')
    await page.screenshot({ path: info.outputPath('sales-analysis-persisted.png'), fullPage: true })
    await analysisRow.getByRole('link', { name: '연결 출하 보기', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/sales/shipments\\?salesOrderId=${order.id}$`))
    await expect(page.getByRole('row').filter({ has: page.getByText(shipment.shipmentNo, { exact: true }) })).toContainText('출하완료')
    await page.goto(`/analytics/sales?itemId=${item.id}`)
    await page.getByRole('link', { name: order.salesOrderNo, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/sales/orders\\?keyword=${order.salesOrderNo}$`))
    await expect(page.getByRole('row').filter({ has: page.getByText(order.salesOrderNo, { exact: true }) })).toContainText('출하완료')
})

test('material browser partial receiving and cancellation reverse only good stock', async ({ page, request }, info) => {
    const headers = await authenticated(request)
    const item = await newItem(request, headers, '자재')
    const partners: Required<components['schemas']['PartnerResponse']>[] = await read(request, 'partners?size=100', headers).then(r => r.content)
    const vendor = partners.find(p => p.partnerType === '발주처')!
    expect(vendor).toBeDefined()
    const created = await request.post(`${api}/purchase-orders`, { headers, data: {
        purchaseOrderNo: `PO-E2E-${Date.now()}`, vendorId: vendor.id, itemId: item.id, qty: 10, unitPrice: 100, dueDate: futureDate(),
    } })
    expect(created.status()).toBe(201)
    const order = await created.json()
    await login(page, 'e2e-material')
    await page.goto('/purchase/receiving')
    await page.getByRole('button', { name: '입고 등록', exact: true }).click()
    await page.getByLabel('발주번호 *', { exact: true }).selectOption(String(order.id))
    await page.getByLabel('총 입고수량 *', { exact: true }).fill('6')
    await page.getByLabel('불량수량 *', { exact: true }).fill('1')
    const receivedResponse = mutation(page, 'receivings', 201)
    await page.getByRole('button', { name: '등록', exact: true }).click()
    const received = await receivedResponse
    const row = await search(page, '입고번호, 발주번호, 발주처, 품번 검색...', received.receiving.receivingNo)
    await expect(row).toContainText('부분합격')
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(5)
    expect((await read(request, `purchase-orders/${order.id}`, headers)).receivedQty).toBe(6)
    await page.goto('/')
    await page.getByLabel('조회 품목', { exact: true }).selectOption(String(item.id))
    await page.getByRole('button', { name: '조회 적용', exact: true }).click()
    const inventoryLink = page.getByRole('link', { name: '실제 재고·Lot 근거 분석', exact: true })
    await expect(inventoryLink).toHaveAttribute('href', `/analytics/inventory?itemId=${item.id}`)
    await inventoryLink.click()
    await expect(page.getByLabel('재고 품목', { exact: true })).toHaveValue(String(item.id))
    await expect(page.getByLabel('수불 시작일', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    const inventory = await read(request, `analytics/inventory/summary?itemId=${item.id}`, headers)
    expect(inventory.summary).toMatchObject({ totalItems: 1, ledgerMismatchItems: 0, lotMismatchItems: 0, inventoryTurnover: null })
    expect(inventory.rows[0]).toMatchObject({ currentStock: 5, ledgerBalance: 5, stockLedgerDelta: 0, recordedLotQty: 5, knownUsableLotQty: 5,
        periodIncreaseQty: 5, periodDecreaseQty: 0, periodNetQty: 5, agedLotQty: 0, unit: 'EA' })
    const inventoryRow = page.getByRole('row').filter({ has: page.getByRole('link', { name: item.itemNo, exact: true }) })
    await expect(inventoryRow).toContainText('5 EA')
    await page.screenshot({ path: info.outputPath('inventory-received.png'), fullPage: true })
    await inventoryRow.getByRole('link', { name: '실제 Lot 원천 보기', exact: true }).click()
    await expect(page.getByLabel('Lot 품목 필터', { exact: true })).toHaveValue(String(item.id))
    await expect(page.getByLabel('Lot 상태 필터', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    await page.getByRole('button', { name: received.lotNo, exact: true }).click()
    const receivedLotDialog = page.getByRole('dialog')
    await expect(receivedLotDialog).toContainText('기록 잔량 5 EA')
    await expect(receivedLotDialog.getByRole('link', { name: `RECEIVING · ${received.receiving.receivingNo}`, exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath('lot-receiving-source.png'), fullPage: true })
    await receivedLotDialog.getByRole('link', { name: `RECEIVING · ${received.receiving.receivingNo}`, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/purchase/receiving\\?keyword=${received.receiving.receivingNo}$`))
    await expect(page.getByRole('row').filter({ has: page.getByText(received.receiving.receivingNo, { exact: true }) })).toContainText('부분합격')
    await page.goto(`/analytics/inventory?itemId=${item.id}`)
    await inventoryRow.getByRole('link', { name: '실제 발주제안 보기', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/purchase/mrp\\?itemId=${item.id}$`))
    await expect(page.getByLabel('표시 품목', { exact: true })).toHaveValue(String(item.id))
    await page.goto(`/analytics/inventory?itemId=${item.id}`)
    await page.getByRole('link', { name: item.itemNo, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/items\\?keyword=${item.itemNo}$`))
    await expect(page.getByRole('row').filter({ has: page.getByText(item.itemNo, { exact: true }) })).toContainText('5')
    await page.goto('/purchase/receiving')
    await search(page, '입고번호, 발주번호, 발주처, 품번 검색...', received.receiving.receivingNo)
    await transition(page, row, '입고 취소')
    await expect(row).toContainText('취소')
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    const cancelled = await read(request, `receivings/${received.receiving.id}`, headers)
    expect(cancelled.reversalTxnNo).toBeTruthy()
    expect((await read(request, `purchase-orders/${order.id}`, headers)).receivedQty).toBe(0)
    await page.reload()
    const persisted = await search(page, '입고번호, 발주번호, 발주처, 품번 검색...', received.receiving.receivingNo)
    await persisted.getByRole('button', { name: '상세', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText(cancelled.reversalTxnNo)
    await page.screenshot({ path: info.outputPath('receiving-reversed.png'), fullPage: true })
    await page.goto(`/inventory/stock?itemId=${item.id}`)
    await expect(page.getByRole('heading', { name: '재고 현황 · 실제 원천 분석', exact: true })).toBeVisible()
    const reversed = await read(request, `analytics/inventory/summary?itemId=${item.id}`, headers)
    expect(reversed.rows[0]).toMatchObject({ currentStock: 0, ledgerBalance: 0, stockLedgerDelta: 0, recordedLotQty: 0,
        periodIncreaseQty: 5, periodDecreaseQty: 5, periodNetQty: 0 })
    await expect(page.getByRole('row').filter({ has: page.getByRole('link', { name: item.itemNo, exact: true }) })).toContainText('−5 EA')
    await page.screenshot({ path: info.outputPath('inventory-reversed.png'), fullPage: true })
    await page.getByRole('link', { name: '실제 Lot 원천 보기', exact: true }).click()
    await page.getByRole('button', { name: received.lotNo, exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('기록 잔량 0 EA · 폐기')
    await expect(page.getByRole('dialog')).toContainText(cancelled.reversalTxnNo)
    await expect(page.getByRole('dialog').getByRole('link', { name: `RECEIVING · ${received.receiving.receivingNo}`, exact: true })).toHaveCount(2)
    await page.screenshot({ path: info.outputPath('lot-receiving-reversed.png'), fullPage: true })
})

test('Spring BOM MRP proposal converts into a persisted purchase without changing stock', async ({ page, request }, info) => {
    const headers = await authenticated(request)
    const product = await newItem(request, headers), material = await newItem(request, headers, '자재')
    const bom = await request.post(`${api}/boms`, { headers, data: {
        bomNo: `BOM-E2E-${Date.now()}`, parentId: product.id, childId: material.id, qty: 2, lossRate: 10,
    } })
    expect(bom.status()).toBe(201)
    const work = await request.post(`${api}/work-orders`, { headers, data: {
        workOrderNo: `WO-MRP-${Date.now()}`, itemId: product.id, qty: 10, startDate: seoulToday(), dueDate: futureDate(),
    } })
    expect(work.status()).toBe(201)
    const partners: Required<components['schemas']['PartnerResponse']>[] = await read(request, 'partners?partnerType=발주처&size=100', headers).then(r => r.content)
    const vendor = partners[0]; expect(vendor).toBeDefined()
    await login(page, 'e2e-material')
    await page.goto('/purchase/mrp')
    await expect(page.getByLabel('계획 종료일', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    await expect(page.getByLabel('표시 품목', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    await expect(page.getByLabel('표시 품목', { exact: true })).toHaveCSS('color', 'rgb(255, 255, 255)')
    await page.getByLabel('표시 품목', { exact: true }).selectOption(String(material.id))
    const row = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: `${material.itemNo} ${material.name}`, exact: true }) })
    await expect(row.getByText('22 EA', { exact: true })).toHaveCount(3)
    await row.getByRole('button', { name: '발주 전환', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await expect(dialog.getByLabel('발주처 *', { exact: true })).toHaveValue('')
    await dialog.getByLabel('발주처 *', { exact: true }).selectOption(String(vendor.id))
    await expect(dialog.getByLabel('제안 수량 (EA) *', { exact: true })).toHaveValue('22')
    await expect(dialog.getByRole('button', { name: '배송 예정일 달력 열기' })).toBeVisible()
    await dialog.getByLabel('배송 예정일 *', { exact: true }).fill(futureDate())
    const response = mutation(page, 'purchase-orders', 201)
    await dialog.getByRole('button', { name: '발주 확정', exact: true }).click()
    const po = await response
    await expect(page.getByRole('status')).toContainText(po.purchaseOrderNo)
    expect(po).toMatchObject({ vendorId: vendor.id, itemId: material.id, qty: 22, amount: 2200, status: '발주' })
    expect((await read(request, `purchase-orders/${po.id}`, headers)).qty).toBe(22)
    expect((await read(request, `items/${material.id}`, headers)).stock).toBe(0)
    await expect(row.getByRole('button', { name: '발주 전환', exact: true })).toHaveCount(0)
    const plan = await read(request, `analytics/mrp/suggestions?itemId=${material.id}`, headers)
    expect(plan.rows[0]).toMatchObject({ grossRequirement: 22, onOrder: 22, suggestedPurchaseQty: 0, action: 'EXPEDITE' })
    await page.reload()
    await page.getByLabel('표시 품목', { exact: true }).selectOption(String(material.id))
    await expect(row).toContainText('공급 납기 조정 필요')
    await page.screenshot({ path: info.outputPath('mrp-purchase-persisted.png'), fullPage: true })
})

test('production analysis reads current actuals, delay and refresh then drills into persisted work', async ({ page, request }, info) => {
    const headers = await authenticated(request), item = await newItem(request, headers)
    const due = addDateDays(seoulToday(), -1)
    const created = await request.post(`${api}/work-orders`, { headers, data: {
        workOrderNo: `WO-ANL-${Date.now()}`, itemId: item.id, qty: 10, startDate: addDateDays(due, -2), dueDate: due,
    } })
    expect(created.status()).toBe(201)
    const work = await created.json()
    expect((await request.post(`${api}/work-orders/${work.id}/progress`, { headers, data: { goodQty: 4, defectQty: 1 } })).status()).toBe(200)
    await login(page, 'e2e-material')
    await page.goto('/')
    await page.getByLabel('조회 품목', { exact: true }).selectOption(String(item.id))
    await page.getByRole('button', { name: '조회 적용', exact: true }).click()
    const analysisLink = page.getByRole('link', { name: '현재 생산 진척·지연 분석', exact: true })
    await expect(analysisLink).toHaveAttribute('href', `/analytics?itemId=${item.id}`)
    await analysisLink.click()
    await expect(page.getByLabel('완료예정 시작일', { exact: true })).toHaveCSS('background-color', 'rgb(14, 23, 38)')
    await expect(page.getByLabel('분석 품목', { exact: true })).toHaveValue(String(item.id))
    await page.getByLabel('오더·품목·담당 검색', { exact: true }).fill(work.workOrderNo)
    await page.getByRole('button', { name: '분석 적용', exact: true }).click()
    const row = page.getByRole('row').filter({ has: page.getByRole('link', { name: work.workOrderNo, exact: true }) })
    await expect(row.getByText('5 EA', { exact: true })).toBeVisible()
    await expect(row.getByText('50% / 80%', { exact: true })).toBeVisible()
    await expect(row.getByText('현재 지연', { exact: true })).toBeVisible()
    const current = await read(request, `analytics/production/progress?itemId=${item.id}`, headers)
    expect(current.summary).toMatchObject({ totalOrders: 1, activeOrders: 1, delayedOrders: 1, meanActiveProgressPercent: 50, meanReportedYieldPercent: 80 })
    // A write uses the existing work-order API; analysis itself only reads.
    expect((await request.post(`${api}/work-orders/${work.id}/progress`, { headers, data: { goodQty: 6, defectQty: 2 } })).status()).toBe(200)
    await page.getByRole('button', { name: '현재 실적 새로고침', exact: true }).click()
    await expect(row.getByText('2 EA', { exact: true })).toHaveCount(2)
    await expect(row.getByText('80% / 75%', { exact: true })).toBeVisible()
    expect((await read(request, `items/${item.id}`, headers)).stock).toBe(0)
    await page.screenshot({ path: info.outputPath('production-analysis-current.png'), fullPage: true })
    await row.getByRole('link', { name: work.workOrderNo, exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/production/orders\\?keyword=${work.workOrderNo}$`))
    await expect(page.getByRole('row').filter({ has: page.getByText(work.workOrderNo, { exact: true }) })).toContainText('진행중')
    await expect(page.getByRole('button', { name: '실적 입력', exact: true })).toHaveCount(0)
})

test('protected return URL, rejected login, session restoration and logout', async ({ page, request }) => {
    expect((await request.get(`${api}/items`)).status()).toBe(401)
    await page.goto('/sales/quotations')
    await expect(page).toHaveURL(/\/login/)
    await page.getByLabel('사용자명').fill('admin')
    await page.getByLabel('비밀번호', { exact: true }).fill('incorrect')
    await page.getByRole('button', { name: '로그인', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('추적 ID:')
    await page.getByLabel('비밀번호', { exact: true }).fill('admin123')
    await page.getByRole('button', { name: '로그인', exact: true }).click()
    await expect(page).toHaveURL(/\/sales\/quotations$/)
    await page.reload()
    await expect(page.getByRole('button', { name: '견적 등록', exact: true })).toBeVisible()
    const user = await read(request, 'auth/me', await authenticated(request))
    await page.getByRole('button', { name: user.name, exact: true }).click()
    await page.getByRole('button', { name: '로그아웃', exact: true }).click()
    await expect(page).toHaveURL(/\/login/)
    await page.goto('/sales/quotations')
    await expect(page).toHaveURL(/\/login/)
})

test('material cannot write sales/production; sales cannot write receiving', async ({ page, request }) => {
    const material = await authenticated(request, 'e2e-material')
    expect((await request.get(`${api}/analytics/sales/summary`, { headers: material })).status()).toBe(403)
    const denied = await request.post(`${api}/shipments`, { headers: material, data: { salesOrderId: 1, lotId: 1, qty: 1, deliveryDate: futureDate() } })
    expect(denied.status()).toBe(403)
    await login(page, 'e2e-material')
    for (const [path, button] of [['/sales/quotations', '견적 등록'], ['/sales/orders', '수주 등록'],
        ['/production/orders', '오더 등록'], ['/sales/shipments', '출하 지시']]) {
        await page.goto(path)
        await expect(page.getByRole('table')).toBeVisible()
        await expect(page.getByRole('button', { name: button, exact: true })).toHaveCount(0)
    }
    await page.goto('/')
    await expect(page.getByRole('heading', { name: '운영 대시보드', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: '실제 영업·미수 요약', exact: true })).toHaveCount(0)
    await page.goto('/analytics/sales')
    await expect(page.getByRole('alert')).toContainText('ADMIN·SALES·ACCOUNTING만 조회')
    const sales = await authenticated(request, 'e2e-sales')
    expect((await request.post(`${api}/receivings`, { headers: sales, data: { purchaseOrderId: 1, receivedQty: 1, defectQty: 0 } })).status()).toBe(403)
    // Remove the prior browser token through the real logout UI.
    await page.getByRole('button', { name: 'e2e-material', exact: true }).click()
    await page.getByRole('button', { name: '로그아웃', exact: true }).click()
    await login(page, 'e2e-sales')
    await page.goto('/purchase/receiving')
    await expect(page.getByRole('table')).toBeVisible()
    await expect(page.getByRole('button', { name: '입고 등록', exact: true })).toHaveCount(0)
})
